image: docker:latest

services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - apk add bash py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

Tests:
  stage: test
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/$CI_COMMIT_REF_SLUG || true
    - ./tests/run.sh
    - docker tag mnj-tox ${CI_REGISTRY_IMAGE}/$CI_COMMIT_REF_SLUG
    - docker push ${CI_REGISTRY_IMAGE}/$CI_COMMIT_REF_SLUG
