language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - python setup.py -q install
  - pip install -q pytest pytest-cov coveralls
script: py.test --cov=mnj
services:
  - mongodb
after_success: coveralls
